language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: 
  api_key:
    secure: qMMgA3Wl+FkLsRI8GS525p4GTvv24TV/Pc/T8dIafWnY/bdAyazeip1p2F1+Cy51jaLmEXWTSG6vsrFzSpHb0haho1mv3YiMG4j+JtoRVOomlCGuJVVAGsQCp7qGMCFN2a9hUVCMMLAUJalId67e2XEJw8EfuZN4xBrEcNpFWt0g/r+9Q06nvJrn5y1peCKFqdBdPK0zZfnGVB+Z1S6n8qOZ1Dd1MnMaqFcPnWSZyI+z0N/fLlkRi3h0OWbgX8zbAub8TysoXzgWYr0srv6xcOkkvEEL/hzWq2eZTEY80ld/taGjvaRaQaiSFQ1yS5uibRaXFimIv8nJv0Elf27v6Fl7IiXa0vye5SR/U7ka9ZoBuYe7qLDk94emaqhNDYV18rbVR8fvbLwC6UyDDLyKuKmTRR1dBQu9wR5JaUo+7iEt1NmCaFnmNahYOd87rbD2kmqX2Hzvq7GbuMXLHMtWlpGKKIDU5kjFc89uOSZDkZEFOoQ7+QS+i5jJVMou21ciIoafDob5T43TiAheYHFe7jd/VFnLZ+r5RXfgAIO0vkHBnUSp+E8J1w9c88xT17cmfFwG7Zn2/2/eQfC7wd9Y5vV/bTpdwp1TXdX9TmjZBqHD14nc4+UEDoEQOs+Xjtg5YVrh8l1nPud5ZAksFlsbJ97Aa4AiJNu8DcDu3uoPOVc=
  app: feed-the-people
  on:
    repo: feed-the-people/Back-End
  run: rails db:migrate
