language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: 
  api_key:
    secure: 
  app: feed-the-people
  on:
    repo: feed-the-people/Back-End
  run: rails db:migrate